version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
      - ./data:/data
    env_file:
      - .env

networks:
  app-network:

volumes:
  db-data:
