spring:
  config:
    import: optional:file:.env[.properties]

  liquibase:
    change-log: classpath*:liquibase/db.changelog.yaml
    enabled: true
    default-schema: public

  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver